# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

AdminUser.create!(email: 'admin@example.com', password: 'password', password_confirmation: 'password')

User.create!(name:'Maggie', state:'Iowa', city: 'Iowa City', profession:'Student', description:'Hi, I am Maggie!')
User.create!(name:'Sushma', state:'Iowa', city: 'Iowa City', profession:'Student', description:'Hi, I am Sushma!')
User.create!(name:'Anu', state:'Michigan', city: 'Milwaki', profession:'Student', description:'Hi, I am Anu!')
User.create!(name:'Jingwei', state:'New York', city: 'New York City', profession:'Student', description:'Hi, I am Jingwei. I am a boy!')



Blog.create!(title:'Blog post1', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:1)
Blog.create!(title:'Blog post2', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:1)
Blog.create!(title:'Blog post3', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:1)
Blog.create!(title:'Blog post4', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:2)
Blog.create!(title:'Blog post5', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:2)
Blog.create!(title:'Blog post6', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:2)
Blog.create!(title:'Blog post7', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:3)
Blog.create!(title:'Blog post8', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:3)
Blog.create!(title:'Blog post9', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:3)
Blog.create!(title:'Blog post10', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:4)
Blog.create!(title:'Blog post11', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:4)
Blog.create!(title:'Blog post12', content:'Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data. Software Engineering Languages and Tools Project Seed Data.',  user_id:4)



